import json
import os

PROFILES_FILE = os.path.join(os.path.dirname(__file__), "profiles.json")


PHONES = [
    {
        "name": "iPhone 16 Pro Max",
        "brand": "Apple",
        "price": 12999,
        "cpu": "A18 Pro",
        "cpu_score": 99,
        "camera": 98,
        "battery": 88,
        "storage_max": 1024,
        "ram": 8,
        "display": '6.9" OLED 120Hz ProMotion',
        "gaming": 98,
        "os": "iOS 18",
        "best_for": ["profissional", "conteudo", "fotos"],
        "highlights": [
            "Chip A18 Pro mais poderoso do mercado",
            "Camera principal 48MP com tetraprism 5x",
            "Gravação de vídeo 4K 120fps ProRes",
            "Display ProMotion LTPO 1–120Hz",
            "Apple Intelligence com IA generativa",
        ],
        "weaknesses": ["Sem expansão de armazenamento", "Preço elevado", "Sem carregamento rápido acima de 30W"],
        "image_emoji": "📱",
    },
    {
        "name": "Samsung Galaxy S25 Ultra",
        "brand": "Samsung",
        "price": 11999,
        "cpu": "Snapdragon 8 Elite",
        "cpu_score": 97,
        "camera": 97,
        "battery": 89,
        "storage_max": 1024,
        "ram": 12,
        "display": '6.9" Dynamic AMOLED 2X 120Hz',
        "gaming": 97,
        "os": "Android 15 / One UI 7",
        "best_for": ["profissional", "conteudo", "fotos", "jogos"],
        "highlights": [
            "Snapdragon 8 Elite top de linha",
            "Camera 200MP + zoom periscópio 5x",
            "S Pen integrada para produtividade",
            "Bateria 5000mAh com carregamento 45W",
            "Galaxy AI para edição e resumos",
        ],
        "weaknesses": ["Preço alto", "Software pesado", "S Pen pode ser desnecessária"],
        "image_emoji": "📲",
    },
    {
        "name": "Google Pixel 9 Pro XL",
        "brand": "Google",
        "price": 9999,
        "cpu": "Google Tensor G4",
        "cpu_score": 85,
        "camera": 99,
        "battery": 87,
        "storage_max": 1024,
        "ram": 16,
        "display": '6.8" LTPO OLED 120Hz',
        "gaming": 78,
        "os": "Android 15 puro",
        "best_for": ["fotos", "profissional", "conteudo"],
        "highlights": [
            "Melhor camera computacional do mundo",
            "IA Google com Gemini integrado",
            "7 anos de atualizações garantidas",
            "Modo astrofotografia único",
            "Funcionalidades Magic Eraser, Best Take",
        ],
        "weaknesses": ["Tensor G4 inferior em gaming", "Ecossistema menor que Apple/Samsung", "Preço premium"],
        "image_emoji": "📸",
    },
    {
        "name": "OnePlus 13",
        "brand": "OnePlus",
        "price": 5999,
        "cpu": "Snapdragon 8 Elite",
        "cpu_score": 97,
        "camera": 82,
        "battery": 97,
        "storage_max": 512,
        "ram": 16,
        "display": '6.82" LTPO AMOLED 120Hz',
        "gaming": 96,
        "os": "OxygenOS 15 / Android 15",
        "best_for": ["jogos", "profissional"],
        "highlights": [
            "Snapdragon 8 Elite com refrigeração vapor",
            "Bateria 6000mAh + carregamento 100W",
            "Carregamento sem fio 50W",
            "UX limpa e rápida OxygenOS",
            "Melhor custo-benefício topo de linha",
        ],
        "weaknesses": ["Camera mediana para o preço", "Marca menos conhecida no Brasil", "Pós-venda limitado"],
        "image_emoji": "⚡",
    },
    {
        "name": "Xiaomi 15 Ultra",
        "brand": "Xiaomi",
        "price": 9499,
        "cpu": "Snapdragon 8 Elite",
        "cpu_score": 97,
        "camera": 96,
        "battery": 92,
        "storage_max": 1024,
        "ram": 16,
        "display": '6.73" LTPO AMOLED 120Hz',
        "gaming": 96,
        "os": "HyperOS 2 / Android 15",
        "best_for": ["fotos", "jogos", "conteudo"],
        "highlights": [
            "Parceria Leica para cameras profissionais",
            "Bateria 5500mAh com carregamento 90W",
            "Camera principal 1 polegada Sony LYT-900",
            "Zoom óptico 5x periscópio Leica",
            "Carregamento sem fio 80W + inverso 10W",
        ],
        "weaknesses": ["MIUI/HyperOS carregado de apps", "Suporte pós-venda no BR limitado", "Updates mais lentos"],
        "image_emoji": "🔭",
    },
    {
        "name": "Samsung Galaxy S25+",
        "brand": "Samsung",
        "price": 7999,
        "cpu": "Snapdragon 8 Elite",
        "cpu_score": 97,
        "camera": 90,
        "battery": 85,
        "storage_max": 512,
        "ram": 12,
        "display": '6.7" Dynamic AMOLED 2X 120Hz',
        "gaming": 95,
        "os": "Android 15 / One UI 7",
        "best_for": ["profissional", "jogos", "estudos"],
        "highlights": [
            "Snapdragon 8 Elite ao melhor preço Samsung",
            "Design mais fino e leve que o Ultra",
            "Ecosystem Samsung perfeito (Watch, Buds, TV)",
            "Galaxy AI embarcado",
            "7 anos de atualizações de segurança",
        ],
        "weaknesses": ["Bateria menor que concorrentes", "Sem S Pen", "Camera inferior ao Ultra"],
        "image_emoji": "💼",
    },
    {
        "name": "iPhone 16",
        "brand": "Apple",
        "price": 7499,
        "cpu": "A18",
        "cpu_score": 95,
        "camera": 90,
        "battery": 85,
        "storage_max": 512,
        "ram": 8,
        "display": '6.1" OLED 60Hz',
        "gaming": 94,
        "os": "iOS 18",
        "best_for": ["estudos", "profissional", "fotos"],
        "highlights": [
            "Chip A18 com Neural Engine avançado",
            "Camera com botão Camera Control",
            "Melhor tela OLED compacta",
            "Apple Intelligence e Siri avançada",
            "Ecossistema Apple completo",
        ],
        "weaknesses": ["Tela 60Hz (não ProMotion)", "Bateria modesta", "Preço alto para 60Hz"],
        "image_emoji": "🍎",
    },
    {
        "name": "Motorola Edge 50 Pro",
        "brand": "Motorola",
        "price": 3499,
        "cpu": "Snapdragon 7s Gen 3",
        "cpu_score": 72,
        "camera": 75,
        "battery": 90,
        "storage_max": 512,
        "ram": 12,
        "display": '6.7" pOLED 144Hz',
        "gaming": 70,
        "os": "Android 14 / Hello UI",
        "best_for": ["estudos", "jogos"],
        "highlights": [
            "Tela pOLED 144Hz curva premium",
            "Carregamento TurboPower 125W ultra rápido",
            "Design fino e elegante",
            "Boa experiência Android puro",
            "Preço acessível para tela OLED",
        ],
        "weaknesses": ["CPU mediocre para gaming pesado", "Camera inconsistente", "Poucas atualizações garantidas"],
        "image_emoji": "🏎️",
    },
    {
        "name": "Realme GT 7 Pro",
        "brand": "Realme",
        "price": 4999,
        "cpu": "Snapdragon 8 Elite",
        "cpu_score": 97,
        "camera": 78,
        "battery": 88,
        "storage_max": 512,
        "ram": 16,
        "display": '6.78" AMOLED 120Hz',
        "gaming": 97,
        "os": "Realme UI 6 / Android 15",
        "best_for": ["jogos"],
        "highlights": [
            "Snapdragon 8 Elite ao menor preço do mercado",
            "Sistema de resfriamento VC avançado",
            "Bateria 6500mAh enorme",
            "Ideal para gaming extremo",
            "RAM 16GB + armazenamento UFS 4.0",
        ],
        "weaknesses": ["Camera abaixo do esperado", "Software com muitos apps desnecessários", "Pouco suporte no BR"],
        "image_emoji": "🎮",
    },
    {
        "name": "Samsung Galaxy A55 5G",
        "brand": "Samsung",
        "price": 2399,
        "cpu": "Exynos 1480",
        "cpu_score": 60,
        "camera": 72,
        "battery": 82,
        "storage_max": 256,
        "ram": 8,
        "display": '6.6" Super AMOLED 120Hz',
        "gaming": 58,
        "os": "Android 14 / One UI 6.1",
        "best_for": ["estudos"],
        "highlights": [
            "Tela Super AMOLED brilhante",
            "4 anos de atualizações Android",
            "Design premium com Gorilla Glass Victus",
            "Bateria 5000mAh confiável",
            "Marca com boa assistência técnica no BR",
        ],
        "weaknesses": ["CPU mediana", "Camera sem recursos avançados", "Sem 5G em todas frequências"],
        "image_emoji": "📚",
    },
    {
        "name": "Poco X7 Pro",
        "brand": "Xiaomi/Poco",
        "price": 2999,
        "cpu": "MediaTek Dimensity 8400 Ultra",
        "cpu_score": 85,
        "camera": 70,
        "battery": 88,
        "storage_max": 512,
        "ram": 12,
        "display": '6.67" AMOLED 120Hz',
        "gaming": 86,
        "os": "HyperOS / Android 15",
        "best_for": ["jogos", "estudos"],
        "highlights": [
            "Dimensity 8400 Ultra excelente para jogos",
            "Bateria 6000mAh com carregamento 90W",
            "Tela AMOLED de alta qualidade",
            "Custo-benefício excepcional para gaming",
            "Armazenamento UFS 4.0 veloz",
        ],
        "weaknesses": ["Camera básica", "Software com anúncios", "Sem NFC em alguns modelos"],
        "image_emoji": "🕹️",
    },
    {
        "name": "Samsung Galaxy Z Fold 6",
        "brand": "Samsung",
        "price": 19999,
        "cpu": "Snapdragon 8 Gen 3",
        "cpu_score": 94,
        "camera": 88,
        "battery": 78,
        "storage_max": 1024,
        "ram": 12,
        "display": '7.6" Dynamic AMOLED 2X (interno) / 6.3" (externo)',
        "gaming": 92,
        "os": "Android 15 / One UI 7",
        "best_for": ["profissional", "estudos", "conteudo"],
        "highlights": [
            "Tela dobrável 7.6\" única no mercado",
            "Multitarefa real com janelas lado a lado",
            "S Pen compatível para notas e desenho",
            "Design premium e durável IPX8",
            "Galaxy AI avançado para produtividade",
        ],
        "weaknesses": ["Bateria ruim para o tamanho", "Preço altíssimo", "Espessura quando dobrado"],
        "image_emoji": "📋",
    },
]

USE_CASES = {
    "estudos": {
        "label": "🎓 Estudos",
        "desc": "Leitura, aulas online, anotações e organização",
        "weights": {"camera": 0.1, "battery": 0.35, "gaming": 0.05, "cpu_score": 0.25, "storage": 0.25},
        "priority_text": "Bateria duradoura e armazenamento para apps e materiais são essenciais.",
    },
    "profissional": {
        "label": "💼 Uso Profissional",
        "desc": "E-mails, videoconferências, multitarefa e produtividade",
        "weights": {"camera": 0.2, "battery": 0.25, "gaming": 0.05, "cpu_score": 0.3, "storage": 0.2},
        "priority_text": "CPU potente para multitarefa e bateria confiável são prioridades.",
    },
    "conteudo": {
        "label": "🎬 Produção de Conteúdo",
        "desc": "Fotos, vídeos, reels e streaming",
        "weights": {"camera": 0.45, "battery": 0.2, "gaming": 0.05, "cpu_score": 0.2, "storage": 0.1},
        "priority_text": "Camera de alta qualidade é o fator mais importante.",
    },
    "jogos": {
        "label": "🎮 Games",
        "desc": "Jogos pesados, streaming de jogos e esports",
        "weights": {"camera": 0.05, "battery": 0.2, "gaming": 0.55, "cpu_score": 0.15, "storage": 0.05},
        "priority_text": "Desempenho em jogos e bateria para longas sessões são cruciais.",
    },
}


def load_profiles():
    if os.path.exists(PROFILES_FILE):
        with open(PROFILES_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_profiles(profiles):
    with open(PROFILES_FILE, "w", encoding="utf-8") as f:
        json.dump(profiles, f, ensure_ascii=False, indent=2)
